version: '3'
services:

  api:
    image: test-api
    build: .
    networks:
      - backend
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
    links:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  stream:
    image: segment/fake-event-stream
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=events
      - EVENTS_PER_SECOND=1
    links:
      - redis

networks:
  backend:
    driver: bridge