version: '3'
services:

  api:
    image: test-api
    build: .
    volumes: 
      - ./:/usr/src/app
    networks:
      - backend
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend

  stream:
    image: segment/fake-event-stream
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=events
      - EVENTS_PER_SECOND=1
    links:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge